# Generated by Django 3.0.7 on 2020-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('web_dev', 'Web Development'), ('data_science', 'Data Science')], default=None, max_length=16, null=True),
        ),
    ]
