# Generated by Django 3.0.7 on 2020-06-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200608_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadCodeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occured', models.DateField(auto_now_add=True)),
                ('resource', models.CharField(max_length=128, null=True)),
                ('resp_code', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occured', models.DateField(auto_now_add=True)),
                ('resource', models.CharField(max_length=128, null=True)),
                ('exc_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('web_dev', 'Web Dev'), ('data_science', 'Data Science')], default=None, max_length=16, null=True),
        ),
    ]
