# Generated by me on 2020-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lang',
            field=models.CharField(choices=[('eng', 'Eng'), ('rus', 'Rus'),], default='eng', max_length=4))
    ]
